import { createFileRoute } from "@tanstack/react-router";
import { LegalLayout, Section } from "@/components/nova/LegalLayout";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Nova AI" },
      { name: "description", content: "The terms that govern your use of Nova AI." },
    ],
  }),
  component: TermsPage,
});

const CONTACT_EMAIL = "anirudhv16742@gmail.com";

function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="July 6, 2026">
      <Section title="Acceptance of terms">
        <p>
          By creating an account or using Nova AI ("Nova", "we", "us"), you agree to these Terms
          of Service and to our <a href="/privacy">Privacy Policy</a>. If you don't agree, please
          don't use Nova.
        </p>
      </Section>

      <Section title="Description of service">
        <p>
          Nova is a voice-first AI assistant that can hold conversations, capture notes, set
          reminders, manage a todo list, remember facts you tell it, analyze images and PDFs, and
          — if you connect your Google account — summarize unread email, draft emails for your
          review, and read or create Google Calendar events on your behalf.
        </p>
      </Section>

      <Section title="AI-generated content">
        <p>
          Nova's replies, summaries, and suggestions are generated by AI (Google Gemini) and may
          be inaccurate, incomplete, or out of date. Don't rely on Nova for medical, legal,
          financial, or other safety-critical decisions, and always verify anything important
          (dates, amounts, addresses) before acting on it.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You're responsible for keeping your login credentials secure and for all activity under
          your account. Provide accurate information when you sign up.
        </p>
      </Section>

      <Section title="Acceptable use">
        <ul>
          <li>Don't use Nova for anything illegal, harmful, or abusive.</li>
          <li>Don't attempt to access another user's data or disrupt the service.</li>
          <li>Don't use the Google connection features for anything beyond what you're asking Nova to do for you personally.</li>
        </ul>
      </Section>

      <Section title="Third-party integrations">
        <p>
          Connecting your Google account is optional and is also governed by Google's own Terms
          of Service. You can disconnect it at any time from Settings → Connections.
        </p>
      </Section>

      <Section title="Your content">
        <p>
          You own the notes, reminders, todos, memories, and conversations you create. You grant
          us a license to store and process that content solely to provide and improve the
          service to you.
        </p>
      </Section>

      <Section title="Disclaimer of warranties">
        <p>
          Nova is provided "as is" and "as available," without warranties of any kind, express or
          implied, including that it will be uninterrupted, error-free, or perfectly accurate.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, Nova AI won't be liable for any indirect,
          incidental, or consequential damages arising from your use of the service.
        </p>
      </Section>

      <Section title="Termination">
        <p>
          You may stop using Nova and delete your account at any time. We may suspend or terminate
          access for violations of these terms.
        </p>
      </Section>

      <Section title="Changes to these terms">
        <p>
          We may update these terms from time to time. Continuing to use Nova after a change means
          you accept the updated terms.
        </p>
      </Section>

      <Section title="Governing law">
        <p>These terms are governed by the laws of [Your Jurisdiction].</p>
      </Section>

      <Section title="Contact">
        <p>Questions about these terms? Email us at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p>
      </Section>
    </LegalLayout>
  );
}
