// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { GOOGLE_CONNECTOR_SCOPES } from '@/lib/google-scopes';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Set them in your .env.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

  // Supabase only exposes the Google access/refresh token on the SIGNED_IN
  // event fired the instant it finishes processing an OAuth redirect — and it
  // does that processing asynchronously right after the client is created, so
  // this listener MUST be registered synchronously here (not from a React
  // effect further down the tree — route guards like `beforeLoad` can call
  // `supabase.auth.getUser()` and trigger/consume that event before any
  // component ever mounts).
  if (typeof window !== 'undefined') {
    client.auth.onAuthStateChange((event, session) => {
      if (event === 'SIGNED_IN' && session?.provider_token) {
        import('@/integrations/google/connections.functions').then(({ saveGoogleConnection }) =>
          saveGoogleConnection({
            data: {
              accessToken: session.provider_token!,
              refreshToken: session.provider_refresh_token ?? null,
              expiresIn: 3600,
              scope: GOOGLE_CONNECTOR_SCOPES,
            },
          }),
        ).catch((err) => console.error('[Google connection] failed to save token:', err));
      }
    });
  }

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
